# Generated by Django 3.2.25 on 2024-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('news_content', models.TextField(verbose_name='Новость')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('date_news', models.DateTimeField(auto_now=True, verbose_name='дата создания новости')),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.CharField(default='Класс', max_length=500, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='Супер', max_length=100, verbose_name='заголовок'),
        ),
    ]
