# Generated by Django 3.2.25 on 2024-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240326_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_news',
            field=models.DateField(auto_now=True, verbose_name='дата создания новости'),
        ),
    ]
